export const defaultBlurDataURL =
  'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMSIgaGVpZ2h0PSIxIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciPjxyZWN0IGZpbGw9IiNlZWVlZWUiIHdpZHRoPSIxIiBoZWlnaHQ9IjEiIHJ4PSIwLjIiIHJ5PSIwLjIiLz48L3N2Zz4=';

export const propertyImagePlaceholder = '/images/placeholders/property-fallback.svg';
